// demo-react/src/components/Menu.tsx
import * as React from 'react';
import { RouteProp } from '@react-navigation/core';
import { FrameNavigationProp } from 'react-nativescript-navigation';
import { MainStackParamList } from './NavigationParamList';

import { demos } from './linked-components/install';
interface MenuProps {
    route: RouteProp<MainStackParamList, 'menu'>;
    navigation: FrameNavigationProp<MainStackParamList, 'menu'>;
}

export function Menu({ navigation }: MenuProps) {
    function goToDemo(component) {
        navigation.navigate(component);
    }

    if (process.env.NODE_ENV === 'development') {
        const Development = demos.find(({ name }) => name === 'Development');
        if (Development) {
            setTimeout(() => {
                navigation.navigate('development');
            }, 0);
        }
    }

    return (
        <scrollView>
            <stackLayout>
                {demos.map((demo) => (
                    <button
                        key={demo.name}
                        onTap={() => {
                            goToDemo(demo.path);
                        }}
                    >
                        {demo.name}
                    </button>
                ))}
            </stackLayout>
        </scrollView>
    );
}

// demo-ng/src/app/menu/menu.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterExtensions } from '@nativescript/angular';
import { demos } from '../linked-components/install.module';

@Component({
    selector: 'ns-menu',
    templateUrl: './menu.component.html'
})
export class MenuComponent implements OnInit {
    demos = demos;
    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {
        if (process.env.NODE_ENV === 'development') {
            const Development = demos.find(({ name }) => name === 'Development');
            if (Development) {
                this.router.navigate([Development.path]);
            }
        }
    }

    goToDemo(component: string): void {
        this.router.navigate([component], {
            animated: true,
            transition: {
                name: 'slideLeft',
                duration: 200,
                curve: 'ease'
            }
        });
    }
}

<ActionBar title="Angular Demo"></ActionBar>

<ScrollView>
    <StackLayout>
        <StackLayout *ngFor="let demo of demos">
            <Button text="{{ demo.name }}" (tap)="goToDemo(demo.path)"></Button>
        </StackLayout>
    </StackLayout>
</ScrollView>
