// demo-snippets/ng/development/development.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterExtensions } from '@nativescript/angular';

@Component({
    selector: 'ns-development',
    templateUrl: './development.component.html'
})
export class DevelopmentComponent implements OnInit {
    public cast: any = null;

    constructor(private router: RouterExtensions) {}

    ngOnInit(): void {}

    goBack(): void {
        this.router.back();
    }

    handleCastEvent(args) {
        console.log(`event: ${args.data.eventName}`);

        if (args.object && !this.cast) {
            this.cast = args.object;
        }
    }
}

<ActionBar>
    <NavigationButton android.systemIcon="ic_menu_back" (tap)="goBack()"></NavigationButton>
    <Label text="Development"></Label>
</ActionBar>

<StackLayout>
    <Label text="This is the development demo..."></Label>
    <CastButton (cast)="handleCastEvent()"></CastButton>
</StackLayout>

// demo-snippets/svelte/Development.svelte
<style>
</style>

<page>
    <actionBar title="Cast Development Demo">
        <navigationButton text="Go back" on:tap={goBack} />
    </actionBar>
    <stackLayout>
        <label text="This is the nativescript-cast development demo..." />
        <castButton on:cast={handleCastEvent} />
    </stackLayout>
</page>

<script lang="typescript">
    import { goBack } from 'svelte-native';

    let cast = null

    const handleCastEvent = (args) => {
        console.log(`event: ${args.data.eventName}`);

        if (args.object && !cast) {
            cast = args.object;
        }
    }
</script>
