// demo-vue/app/components/Development.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="$navigateBack" />
            <Label text="Development Demo" />
        </ActionBar>

        <StackLayout>
            <Label text="This is the development demo." />
        </StackLayout>
    </Page>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped></style>

// demo-svelte/app/Development.svelte
<style type="text/scss">
</style>

<page>
    <actionBar title="Development">
        <navigationButton text="Go back" android.systemIcon="ic_menu_back" on:tap="{goBack}"></navigationButton>
    </actionBar>
    <stackLayout><label text="This is the development demo!"></label></stackLayout>
</page>

<script lang="typescript">
    import { goBack } from 'svelte-native';
</script>
