// demo-svelte/app/Demo1.svelte
<style type="text/scss">
</style>

<page>
    <actionBar title="Demo 1">
        <navigationButton text="Go back" android.systemIcon="ic_menu_back" on:tap="{goBack}"></navigationButton>
    </actionBar>
    <stackLayout>
        <label text="The version is:"></label>
        <versionNumber></versionNumber>
    </stackLayout>
</page>

<script lang="typescript">
    import { goBack } from 'svelte-native';
</script>

// demo-snippets/vue/Demo1.vue
<template>
    <Page>
        <ActionBar>
            <NavigationButton text="Back" android.systemIcon="ic_menu_back" @tap="$navigateBack" />
            <Label text="Demo 1" />
        </ActionBar>

        <StackLayout>
            <Label text="The version is:" />
            <VersionNumber />
        </StackLayout>
    </Page>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped></style>
